# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="totnopj-ju30958"

[default]
account = "totnopj-ju30958"
user = "RANIADER"
password = "W77Sbk4sZcARz8J"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
